### ISSUE TITLE
Move DAO multisig to L2

### ISSUE THREAD

**Issue by ajsantander** [ethernautdao/ethernauts#19]
### Subtasks
- [x] Confirm decision
- [x] Audit https://ogg.scopelift.co/
- [x] Create new multisig with same addresses as L1 - Done `0x8cbecc838DEA01d3dd6828615a38fc4486D9F326`
- [x] Validate multisig instance bytecode - Matches
- [x] Test L2 multisig - Sent it 0.03 ETH and back
- [x] Send existing funds to L2
  - [x] Agree on method - will send 12k sUSD to one of the signer addresses, swap it to USDC or DAI, bridge it to L2, then send it to the multisig on L2 
  - [x] Send all sUSD to an EOA - sending to `0x45a10F35BeFa4aB841c77860204b133118B7CcAE`
  - [x] Swap all sUSD to DAI
  - [x] Bridge all DAI to L2
  - [x] Send DAI to multisig
- [x] Verify multisig on Etherscan

**Comment by ajsantander** [comment]
Multisig wallet audit for https://ogg.scopelift.co/

This is the source code of the wallet:
https://github.com/ScopeLift/ovm-og-multisigwallet/commits/master

This is a diagram that studies how this wallet results from minor variations to the original Gnosis Multisig wallet:
https://app.diagrams.net/#G1JXWJ_VHAdySWCKfK3pxwxBEeQpZ1yc0
![multisig-history](https://user-images.githubusercontent.com/550409/133683424-70896d5f-42a3-42bb-b2c6-45a4180c0520.jpg)
m

The diagram can be used to demonstrate that the code does not contain any malicious changes from the original code, which was audited multiple times (previous audit links in the diagram).

I've made a couple utilities to validate that the bytecode of the instance produced by the dapps factory matches the expected bytecode, in case optimistic etherscan can't do it for us.
https://github.com/ajsantander/ovm-og-multisigwallet
